name: Deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
      - run: |
          npm install -g yarn
          yarn
          yarn build

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./.output/"
          target: "/var/www/blog.necodeo.com/admin"

      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/blog.necodeo.com/admin/
            source ~/.nvm/nvm.sh
            nvm install 18.17.0
            nvm use 18.17.0
            lsof -i:3000 -t | xargs -r kill
            API_URL=http://admin-api.necodeo.com/api/v1 PORT=3000 node .output/server/index.mjs
